### ISSUE TITLE
Score Board

### ISSUE THREAD

**Issue by harshitg00** [harshitg00/snake_game#1]
Create a scoreboard that shows names of top 10 scorers. 
An option to be added that will ask for user's name after game is over.

**Comment by harris2310** [comment]
I think you need to plug in firebase or something like that cause github pages alone only handles static webapps

**Comment by harshitg00** [comment]
@harris2310 I didn't know that, Thanks for the advice. Will look into it.

**Comment by harris2310** [comment]
I can help you with the backend if you want. I was looking to work on something anyway. It should be simple enough considering there isn't much functionality thats needed

**Comment by harshitg00** [comment]
@harris2310 That would be great actually!

**Comment by harris2310** [comment]
Cool! I'm looking into it!

**Comment by harris2310** [comment]
Hey there!! I'm almost done with the snake game. I added a leaderboard which is attached to the a firebase database. It's free of course for the amount of data the game will handle. The only problem is that when you upload it to github pages your api keys will be vulnerable because there is not backend. Maybe you can pass them in as enviroment variables i'm not sure. I'll look into it!! For now i'll commit the code as is. Ask me anything you want about how to set up firebase !!
